#!/bin/bash

script_name=`basename $0`

framerate=29.97
bitrate=500k
src_extension=.jpg
use_ffmpeg=n

while getopts "r:b:e:g" flag; do
  case $flag in
    r ) framerate=$OPTARG;;
    b ) bitrate=$OPTARG;;
    e ) src_extension=$OPTARG;;
    g ) use_ffmpeg=y;;
  esac
done
shift $((OPTIND-1)); OPTIND=1

src_path=$1
out_path=$2

# FIXME: detect if neither avconv or ffmpeg is installed
# if [ hash avconv 2>/dev/null ]; then
#   if [ hash ffmpeg 2>/dev/null  ]; then
#     echo "no avconv: using ffmpeg"
#     use_ffmpeg=y
#   else
#     echo "$script_name requires either avconv or ffmpeg"
#     exit 0
#   fi
# fi

if [ -z "$src_path" -o -z "$out_path" ]; then
  echo "USAGE:
  $script_name [-r <framerate>] [-b <bitrate>] [-e <source file extension]
  [-g] <source-path> <output-path>"
  exit 0
fi

out_path=$(dirname $out_path)/$(basename $out_path)

function encode_one_series() {
  local name output overwrite src tmp wd
  src=$(cd $1; pwd)
  name=$(basename $src)
  output=$out_path/$name.mp4
  tmp=/tmp/enc-series

  echo "encoding $output"
  if [ -e $output ]; then
    read -n 1 -p "File exists; overwrite? [y/N] " overwrite && echo -en "\n"
    if [[ $overwrite =~ ^[Nn]*$ ]]; then
      return 0
    fi
  fi

  rm -rf $tmp/*
  mkdir -p $tmp
  i=0
  echo "$(ls -1 $src | wc -l) images in the series"
  echo "linking series for encoding"
  for file in $src/*$src_extension; do
    i=$(($i+1))
    padded=$i
    while [ ${#padded} -lt 6 ]; do
      padded=0$padded
    done
    ln -s $file $tmp/$padded$src_extension
  done

  if [ $use_ffmpeg = y ]; then
    ffmpeg \
      -r $framerate \
      -i $tmp/%6d$src_extension \
      -b $bitrate \
      -vcodec libx264 \
      $output
  else
    avconv \
      -r $framerate \
      -i $tmp/%06d$src_extension \
      -b $bitrate \
      -c\:v libx264 \
      $output
    # TODO; enable 2-pass encoding
  fi
}
if [ -n "$(ls -d $src_path/*/)" ]; then
  read -n 1 -p "Encode each subdirectory as a video? [Y/n] " encode_each && echo -en "\n"
  if [[ $encode_each =~ ^[Yy]*$ ]]; then
    for subdir in $(ls -d $src_path/*/); do
      encode_one_series $subdir
    done
  else
    encode_one_series $src_path
  fi
fi
